//Generated by wsdl2apex

public class crmasiaDaimlerApacComSfdcnotificatio {
    public class SFDCNotificationResponseMessageType {
        public String TransactionId;
        public  SFDCNotificationFaultType f=new SFDCNotificationFaultType();
        private String[] TransactionId_type_info = new String[]{'TransactionId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://crmasia.daimler-apac.com/SFDCNotification_1.0','false','false'};
        private String[] field_order_type_info = new String[]{'TransactionId'};
    }
    public class SPOCustomerNotificationRequestMessageType {
        public String Organization;
        public String MarketDiscriminator;
        public String CustomerId;
        public String DealerId;
        private String[] Organization_type_info = new String[]{'Organization','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] MarketDiscriminator_type_info = new String[]{'MarketDiscriminator','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] CustomerId_type_info = new String[]{'CustomerId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] DealerId_type_info = new String[]{'DealerId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://crmasia.daimler-apac.com/SFDCNotification_1.0','true','false'};
        private String[] field_order_type_info = new String[]{'Organization','MarketDiscriminator','CustomerId','DealerId'};
    }
    public class SARICustomerNotificationRequestMessageType {
        public String Organization;
        public String MarketDiscriminator;
        public String Usecase;
        public String RTCustomerId;
        public String DealerId;
        public String CorrelationId;
        private String[] Organization_type_info = new String[]{'Organization','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] MarketDiscriminator_type_info = new String[]{'MarketDiscriminator','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] Usecase_type_info = new String[]{'Usecase','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] RTCustomerId_type_info = new String[]{'RTCustomerId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] DealerId_type_info = new String[]{'DealerId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] CorrelationId_type_info = new String[]{'CorrelationId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://crmasia.daimler-apac.com/SFDCNotification_1.0','true','false'};
        private String[] field_order_type_info = new String[]{'Organization','MarketDiscriminator','Usecase','RTCustomerId','DealerId','CorrelationId'};
    }
    public class SARILeadNotificationRequestMessageType {
        public String Organization;
        public String MarketDiscriminator;
        public String Usecase;
        public String LeadId;
        public String DealerId;
        public String CorrelationId;
        private String[] Organization_type_info = new String[]{'Organization','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] MarketDiscriminator_type_info = new String[]{'MarketDiscriminator','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] Usecase_type_info = new String[]{'Usecase','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] LeadId_type_info = new String[]{'LeadId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] DealerId_type_info = new String[]{'DealerId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] CorrelationId_type_info = new String[]{'CorrelationId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://crmasia.daimler-apac.com/SFDCNotification_1.0','true','false'};
        private String[] field_order_type_info = new String[]{'Organization','MarketDiscriminator','Usecase','LeadId','DealerId','CorrelationId'};
    }
    public class SFDCNotificationFaultType {
        public String TransactionId;
        public String ErrorCode;
        public String ErrorMessageText;
        public String ErrorType;
        private String[] TransactionId_type_info = new String[]{'TransactionId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] ErrorCode_type_info = new String[]{'ErrorCode','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] ErrorMessageText_type_info = new String[]{'ErrorMessageText','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] ErrorType_type_info = new String[]{'ErrorType','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://crmasia.daimler-apac.com/SFDCNotification_1.0','true','false'};
        private String[] field_order_type_info = new String[]{'TransactionId','ErrorCode','ErrorMessageText','ErrorType'};
    }
    public class JPOSCustomerNotificationRequestMessageType {
        public String Organization;
        public String MarketDiscriminator;
        public String CustomerId;
        public String AddressId;
        public String UserId;
        private String[] Organization_type_info = new String[]{'Organization','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] MarketDiscriminator_type_info = new String[]{'MarketDiscriminator','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] CustomerId_type_info = new String[]{'CustomerId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] AddressId_type_info = new String[]{'AddressId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] UserId_type_info = new String[]{'UserId','http://crmasia.daimler-apac.com/SFDCNotification_1.0',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://crmasia.daimler-apac.com/SFDCNotification_1.0','true','false'};
        private String[] field_order_type_info = new String[]{'Organization','MarketDiscriminator','CustomerId','AddressId','UserId'};
    }
    public class SFDCNotificationPort {
        public String endpoint_x = UtilCustomSettings.getWebserviceUrl('EPUrlSfdcNotification');
        public Map<String,String> inputHttpHeaders_x;
        public Map<String,String> outputHttpHeaders_x;
        public String clientCertName_x;
        public String clientCert_x;
        public String clientCertPasswd_x;
        public Integer timeout_x=70000;
        private String[] ns_map_type_info = new String[]{'http://crmasia.daimler-apac.com/SFDCNotification_1.0', 'crmasiaDaimlerApacComSfdcnotificatio'};
        public String SARILeadNotification(String Organization,String MarketDiscriminator,String Usecase,String LeadId,String DealerId,String CorrelationId) {
            crmasiaDaimlerApacComSfdcnotificatio.SARILeadNotificationRequestMessageType request_x = new crmasiaDaimlerApacComSfdcnotificatio.SARILeadNotificationRequestMessageType();
            request_x.Organization = Organization;
            request_x.MarketDiscriminator = MarketDiscriminator;
            request_x.Usecase = Usecase;
            request_x.LeadId = LeadId;
            request_x.DealerId = DealerId;
            request_x.CorrelationId = CorrelationId;
            crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType response_x;
            Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType> response_map_x = new Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'SARILeadNotificationRequest',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'SFDCNotificationResponse',
              'crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.TransactionId;
        }
        public String SARICustomerNotification(String Organization,String MarketDiscriminator,String Usecase,String RTCustomerId,String DealerId,String CorrelationId) {
            crmasiaDaimlerApacComSfdcnotificatio.SARICustomerNotificationRequestMessageType request_x = new crmasiaDaimlerApacComSfdcnotificatio.SARICustomerNotificationRequestMessageType();
            request_x.Organization = Organization;
            request_x.MarketDiscriminator = MarketDiscriminator;
            request_x.Usecase = Usecase;
            request_x.RTCustomerId = RTCustomerId;
            request_x.DealerId = DealerId;
            request_x.CorrelationId = CorrelationId;
            crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType response_x;
            Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType> response_map_x = new Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'SARICustomerNotificationRequest',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'SFDCNotificationResponse',
              'crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.TransactionId;
        }
        public String JPOSCustomerNotification(String Organization,String MarketDiscriminator,String CustomerId,String AddressId,String UserId) {
            crmasiaDaimlerApacComSfdcnotificatio.JPOSCustomerNotificationRequestMessageType request_x = new crmasiaDaimlerApacComSfdcnotificatio.JPOSCustomerNotificationRequestMessageType();
            request_x.Organization = Organization;
            request_x.MarketDiscriminator = MarketDiscriminator;
            request_x.CustomerId = CustomerId;
            request_x.AddressId = AddressId;
            request_x.UserId = UserId;
            crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType response_x;
            Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType> response_map_x = new Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType>();
            response_map_x.put('response_x', response_x);
            SFDCNotificationFaultType fault=new SFDCNotificationFaultType();
             crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationFaultType fal=new crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationFaultType();
                
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'JPOSCustomerNotificationRequest',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'SFDCNotificationResponse',
              'crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType'}
            );
             
           
            response_x = response_map_x.get('response_x');
            String tranaction;
             fal.ErrorCode=response_x.f.ErrorCode;
             System.debug('@@@@@@  fal.ErrorCode'+fal.ErrorCode);
            String falutcodes=fault.ErrorMessageText;
             System.debug('@@@@@@ falutcodes'+falutcodes);
            tranaction=response_x.TransactionId +' '+ response_x.f.TransactionId;
            tranaction=response_x.f.TransactionId;
            tranaction=response_x.f.ErrorCode;
            System.debug('@@@@@@ tranaction'+tranaction);
            System.debug('@@@@@@ response_x'+response_x);
            return response_x.TransactionId;
        }
        public String SPOCustomerNotification(String Organization,String MarketDiscriminator,String CustomerId,String DealerId) {
            crmasiaDaimlerApacComSfdcnotificatio.SPOCustomerNotificationRequestMessageType request_x = new crmasiaDaimlerApacComSfdcnotificatio.SPOCustomerNotificationRequestMessageType();
            request_x.Organization = Organization;
            request_x.MarketDiscriminator = MarketDiscriminator;
            request_x.CustomerId = CustomerId;
            request_x.DealerId = DealerId;
            crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType response_x;
            Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType> response_map_x = new Map<String, crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'SPOCustomerNotificationRequest',
              'http://crmasia.daimler-apac.com/SFDCNotification_1.0',
              'SFDCNotificationResponse',
              'crmasiaDaimlerApacComSfdcnotificatio.SFDCNotificationResponseMessageType'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.TransactionId;
        }
    }
}