/***********************************************************************************
Created By          :    venky    
Created Date        :    2018-08-15
Company             :    NTT Data,Inc.
Usage               :    Created scheduler class to schedule batch class  DeleteInvalidCSVCampaignMembers.
Business Conditions :
*   
JIRA NO             :        

MODIFICATION DETAILS:

1. Modified By      :     
Modifide Date    :   
************************************************************************************/
global class SchDeleteInvalidCSVCampaignMembers implements Schedulable    {
    
    global void execute(SchedulableContext sc){
      /*  DeleteInvalidCSVCampaignMembers batch=new DeleteInvalidCSVCampaignMembers();
        database.executeBatch(batch,1);*/
    }   
}